name:                TypeCheckKaomoji
version:             0.1.0.0
github:              "Krantz-XRF/reanimate-projects"
license:             AGPL-3
author:              "Krantz-XRF"
maintainer:          "Krantz.XRF@outlook.com"
copyright:           "(c) Krantz 2020"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Animation for Typechecking a Kaomoji.
category:            Animation

description:         Please see the README on GitHub at <https://github.com/Krantz-XRF/reanimate-projects/tree/master/TypeCheckKaomoji#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell
- text
- mtl
- lens
- reanimate
- reanimate-svg
- JuicyPixels
- common

default-extensions:
# Type level goodies
- ConstraintKinds
- DataKinds
- TypeOperators
- RankNTypes
# Deriving
- DeriveFunctor
- DeriveFoldable
- DeriveGeneric
- DeriveLift
- DeriveAnyClass
- DeriveTraversable
- DerivingStrategies
- GeneralizedNewtypeDeriving
- StandaloneDeriving
# Flexible type classes
- FlexibleContexts
- FlexibleInstances
- QuantifiedConstraints
- MultiParamTypeClasses
- FunctionalDependencies
# Type applications
- TypeApplications
- ScopedTypeVariables
# Pattern synonyms
- PatternSynonyms
# Grammar candies
- ViewPatterns
- LambdaCase
- TupleSections
- BangPatterns
- RecordWildCards

library:
  source-dirs: src
  ghc-options:
  - -Wall

executables:
  TypeCheckKaomoji-anim:
    main:                Anim.hs
    source-dirs:         anim
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TypeCheckKaomoji
