resolver: lts-16.20

packages:
- common
- 2048IsHard
- 3SAT
- TypeCheckKaomoji

extra-deps:
- git: https://github.com/reanimate/reanimate.git
  commit: ccc69c0d834b821ec6469c1ecee9cb88c39c1704
- reanimate-svg-0.13.0.0
- hgeometry-0.11.0.0
- hgeometry-combinatorial-0.11.0.0
- vinyl-0.13.0
