resolver: lts-16.20

packages:
- common
- 2048IsHard
- 3SAT

extra-deps:
- git: git://github.com/Krantz-XRF/reanimate.git
  commit: ca62e350b86842ed218257489d1106cd888f03e8
- reanimate-svg-0.13.0.0
- hgeometry-0.11.0.0
- hgeometry-combinatorial-0.11.0.0
- vinyl-0.13.0
