resolver: lts-16.20

packages:
- common
- 2048IsHard
- 3SAT
- TypeCheckKaomoji

extra-deps:
- reanimate-1.1.2.1
- reanimate-svg-0.13.0.0
- hgeometry-0.11.0.0
- hgeometry-combinatorial-0.11.0.0
- vinyl-0.13.0
