resolver: lts-16.8

packages:
- common
- 2048IsHard
- 3SAT

extra-deps:
- earcut-0.1.0.4
- reanimate-svg-0.10.0.0
- git: git://github.com/Lemmih/reanimate.git
  commit: 9cf33b9444c5212f47e42497ad6e38d8e5e3b0d8
