name:                2048IsHard
version:             0.1.0.0
github:              "Krantz-XRF/2048IsHard"
license:             AGPL-3
author:              "Krantz-XRF"
maintainer:          "Krantz.XRF@outlook.com"
copyright:           "(c) Krantz 2020"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Animation for 2048 is Hard.
category:            Animation

description:         Please see the README on GitHub at <https://github.com/Krantz-XRF/2048IsHard#readme>

dependencies:
- base >= 4.7 && < 5
- reanimate

library:
  source-dirs: src
  ghc-options:
  - -Wall

executables:
  2048IsHard-anim:
    main:                Main.hs
    source-dirs:         anim
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 2048IsHard
