on:
  push:
    branches:
    - master

name: build
jobs:
  build:
    name: Build and Deploy Doc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        enable-stack: true
        stack-no-global: true
    - name: Install blas/lapack
      run: sudo apt-get install -y libblas-dev liblapack-dev
    - run: stack haddock
    - name: Find Local Doc Root
      run: echo "DOC_PATH=$(python3 -c "import os.path; print(os.path.relpath(r'$(stack path --local-doc-root)', r'$(stack path --project-root)'))")" >> $GITHUB_ENV
    - name: Deploy Documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ env.DOC_PATH }}
        force_orphan: true
